/* Generated By:JJTree: Do not edit this line. ASTTimes.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.company.parser;

import com.company.*;

public
class ASTTimes extends SimpleNode {
  public ASTTimes(int id) {
    super(id);
  }

  public ASTTimes(Griddy p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GriddyVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=beca8c95e7d008c503b49788e94b7f62 (do not edit this line) */
