/* Generated By:JavaCC: Do not edit this line. GriddyVisitor.java Version 7.0.10 */
package com.company.parser;

import com.company.*;

public interface GriddyVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTSetup node, Object data);
  public Object visit(ASTGame node, Object data);
  public Object visit(ASTBoard node, Object data);
  public Object visit(ASTAssign node, Object data);
  public Object visit(ASTIdent node, Object data);
  public Object visit(ASTExpr node, Object data);
  public Object visit(ASTAdd node, Object data);
  public Object visit(ASTMult node, Object data);
  public Object visit(ASTInteger node, Object data);
}
/* JavaCC - OriginalChecksum=7702e0c587b285439ab6b902a61b2db7 (do not edit this line) */
