/* Generated By:JavaCC: Do not edit this line. GriddyVisitor.java Version 7.0.10 */
package com.company.parser;

import com.company.*;

public interface GriddyVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTSetup node, Object data);
  public Object visit(ASTGame node, Object data);
  public Object visit(ASTBoard node, Object data);
  public Object visit(ASTAssign node, Object data);
  public Object visit(ASTIdent node, Object data);
  public Object visit(ASTExpr node, Object data);
  public Object visit(ASTAdd node, Object data);
  public Object visit(ASTMult node, Object data);
  public Object visit(ASTInteger node, Object data);
  public Object visit(ASTString node, Object data);
}
/* JavaCC - OriginalChecksum=ea680bcedf2d342462d5f4164e73ccda (do not edit this line) */
