/* Generated By:JavaCC: Do not edit this line. GriddyTreeConstants.java Version 7.0.10 */
package com.company.parser;

import com.company.*;

public interface GriddyTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSETUP = 1;
  public int JJTVOID = 2;
  public int JJTGAME = 3;
  public int JJTBOARD = 4;
  public int JJTASSIGN = 5;
  public int JJTEXPR = 6;
  public int JJTOPERATOR = 7;
  public int JJTIDENT = 8;
  public int JJTINTEGER = 9;
  public int JJTBOOL = 10;
  public int JJTSTRING = 11;
  public int JJTECHO = 12;


  public String[] jjtNodeName = {
    "Start",
    "Setup",
    "void",
    "Game",
    "Board",
    "Assign",
    "Expr",
    "Operator",
    "Ident",
    "Integer",
    "Bool",
    "String",
    "Echo",
  };
}
/* JavaCC - OriginalChecksum=f140ff4b32d1746a1855ed7cbb5e1887 (do not edit this line) */
