/* Generated By:JavaCC: Do not edit this line. GriddyTreeConstants.java Version 7.0.10 */
package com.company.parser;

import com.company.*;

public interface GriddyTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSETUP = 1;
  public int JJTVOID = 2;
  public int JJTGAME = 3;
  public int JJTBOARD = 4;
  public int JJTASSIGN = 5;
  public int JJTMUL = 6;
  public int JJTDIV = 7;
  public int JJTMOD = 8;
  public int JJTADD = 9;
  public int JJTSUB = 10;
  public int JJTIDENT = 11;
  public int JJTINTEGER = 12;
  public int JJTSTRING = 13;
  public int JJTECHO = 14;


  public String[] jjtNodeName = {
    "Start",
    "Setup",
    "void",
    "Game",
    "Board",
    "Assign",
    "Mul",
    "Div",
    "Mod",
    "Add",
    "Sub",
    "Ident",
    "Integer",
    "String",
    "Echo",
  };
}
/* JavaCC - OriginalChecksum=3437a1c4804ba169290768dd3aea41f3 (do not edit this line) */
