/* Generated By:JavaCC: Do not edit this line. GriddyVisitor.java Version 7.0.10 */
package com.company.parser;

import com.company.*;

public interface GriddyVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTSetup node, Object data);
  public Object visit(ASTGame node, Object data);
  public Object visit(ASTPlace node, Object data);
  public Object visit(ASTPosition node, Object data);
  public Object visit(ASTBoard node, Object data);
  public Object visit(ASTAccess node, Object data);
  public Object visit(ASTPosition node, Object data);
  public Object visit(ASTPiece node, Object data);
  public Object visit(ASTAssign node, Object data);
  public Object visit(ASTEmpty node, Object data);
  public Object visit(ASTExpr node, Object data);
  public Object visit(ASTOperator node, Object data);
  public Object visit(ASTIdent node, Object data);
  public Object visit(ASTInteger node, Object data);
  public Object visit(ASTBool node, Object data);
  public Object visit(ASTString node, Object data);
  public Object visit(ASTOutput node, Object data);
}
/* JavaCC - OriginalChecksum=89781b4b9b82e9e5accc63344d4d5045 (do not edit this line) */
