/* Generated By:JavaCC: Do not edit this line. GriddyDefaultVisitor.java Version 7.0.10 */
package com.company.parser;

import com.company.*;

public class GriddyDefaultVisitor implements GriddyVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTGame node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTPlace node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTPosition node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBoard node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAccess node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTPiece node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAssign node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTEmpty node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTOperator node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIdent node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTInteger node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBoolean node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTString node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTOutput node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=b497540310b3156e01f1da92f719971d (do not edit this line) */
