/* Generated By:JavaCC: Do not edit this line. GriddyTreeConstants.java Version 7.0.10 */
package com.company.parser;

import com.company.*;

public interface GriddyTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSETUP = 1;
  public int JJTVOID = 2;
  public int JJTGAME = 3;
  public int JJTBOARD = 4;
  public int JJTASSIGN = 5;
  public int JJTIDENT = 6;
  public int JJTEXPR = 7;
  public int JJTADD = 8;
  public int JJTMULT = 9;
  public int JJTINTEGER = 10;


  public String[] jjtNodeName = {
    "Start",
    "Setup",
    "void",
    "Game",
    "Board",
    "Assign",
    "Ident",
    "Expr",
    "Add",
    "Mult",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=61fd770b92f3de4bb9ed2c242f0772f8 (do not edit this line) */
