package com.company.codegen;

import com.company.Util;

public class TargetC implements TargetFormat {
    public String formatPieceDef(String ident, GriddyStructure.SetupStruct.PieceDef pieceDef) {
        var displayName = pieceDef.pieceProps.name;
        return ident + ".name = calloc(" + (displayName.length() + 1) + ", sizeof(char));\n"
                + "strcpy(" + ident + ".name, \"" + displayName + "\");\n"
                + ident + ".limit = " + pieceDef.pieceProps.limit + ";\n"
                + ident + ".count = " + pieceDef.pieceProps.count + ";\n"
                + ident + ".capture = " + (pieceDef.pieceProps.capture ? "1" : "0") + ";\n"
                + ident + ".can_jump = " + (pieceDef.pieceProps.canJump ? "1" : "0") + ";\n"
                + ident + ".placeable = " + (pieceDef.pieceProps.placeable ? "1" : "0") + ";\n"
                + ident + ".player = &" + pieceDef.ownerPrefix + ";\n";
    }

    public String formatPlayerDef(GriddyStructure.SetupStruct.PlayerDef playerDef) {
        var out = new StringBuilder();

        out.append("struct Player {\n");
        playerDef.player1.forEach((k, _v) -> out.append("  struct Piece ").append(k).append(";\n"));
        out.append("} _p1, _p2;\n");
        playerDef.player1.forEach((_k, v) ->
            out.append(v.toString())
        );
        playerDef.player2.forEach((_k, v) ->
            out.append(v.toString())
        );

        return out.toString();
    };

    public String formatSetup(GriddyStructure.SetupStruct setupStruct) {
        var out = new StringBuilder("""
                /*    SETUP    */
                """);

        out.append(setupStruct.playerDef)
                .append("struct Piece *_board[")
                .append(setupStruct.boardHeight)
                .append("][")
                .append(setupStruct.boardWidth)
                .append("] = {");

        for (GriddyStructure.SetupStruct.PieceDef[] row : setupStruct.getBoard()) {
            out.append("{");
            for (GriddyStructure.SetupStruct.PieceDef pieceDef : row)
                if (pieceDef != null) {
                    out.append("&")
                            .append(pieceDef.ownerPrefix)
                            .append(".")
                            .append(pieceDef.pieceProps.name)
                            .append(",");
                } else out.append("NULL,");

            out.append("},");
        }

        return out.append("};\n")
                .append("""
                    struct Player * _current_player;
                    int _turn_count = 0;
                    int _win_condition = 0;
                    """)
                .append(setupStruct.body.toString())
                .toString();
    }

    public String formatGame(String body, String winCond) {
        return """
        /*   GAME    */
        do {
        _current_player = _turn_count % 2 ? &_p2 : &_p1;
        """
        + body
        + """
        _win_condition"""
        + " = "
        + winCond
        + ";\n"
        + """
        _turn_count++;
        } while (!_win_condition);
        
        """;
    }

    public String format(GriddyStructure.SetupStruct setupStruct, GriddyStructure.GameStruct gameStruct) {
        return """
                /* === Code generated by Griddy compiler === */
                #include <stdio.h>
                #include <stdlib.h>
                #include <string.h>
                #include <stdbool.h>

                int main(int argc, char *argv[]){
                struct Piece {
                char* name;
                unsigned int limit;
                unsigned int count;
                bool placeable;
                bool capture;
                bool can_jump;
                struct Player* player;
                };
                """
                + setupStruct
                + "\n"
                + gameStruct
                + """
                return 0;
                }
                """;
    }

    public String formatTurn(String playerPrefix, String body) {
        return "_current_player = &" + playerPrefix + ";\n" + body + "\n";
    }

    public String outputString(String body) {
        return "printf(\"%s\\n\", " + body + ");\n";
    }

    public String outputNumber(String body) {
        return "printf(\"%d\\n\", " + body + ");\n";
    }

    public String outputTable(String ident, int w, int h) {
        var letterRow = new StringBuilder();
        for (int n : Util.range(1, w))
            letterRow.append("  ").append((char)('a' + n - 1)).append(" ");

        return "printf(\"┌───" + "┬───".repeat(Math.max(0, w - 1)) + "┐\\n\");\n"
                + "for (int _i = " + (h - 1) + "; _i >= 0; _i--) {\n"
                + "for (int _j = 0; _j < " + w + "; _j++)\n"
                + """
                if (_board[_i][_j]) {
                if (_board[_i][_j]->player == &_p1) {
                printf("│ \\x1b[33m\\x1b[1m%c\\x1b[0m ", *_board[_i][_j]->name);
                } else {
                printf("│ %c ", *_board[_i][_j]->name);
                }
                } else printf("│   ");
                printf("│ %d\\n", _i + 1);
                """
                + "if (_i > 0) printf(\"├───" + "┼───".repeat(Math.max(0, w - 1)) + "┤\\n\");\n}\n"
                + "printf(\"└───" + "┴───".repeat(Math.max(0, w - 1)) + "┘\\n\");\n"
                + "printf(\"" + letterRow + "\\n\");\n";
    }

    public String condStmt(String condition, String body) {
        return "if (" + condition + ")\n" + body;
    }

    public String condElse(String body) {
        return "else\n" + body;
    }

    public String assignPieceRef(String ident, int x, int y) {
        return "struct Piece * " + ident + " = " + formatPieceRef(x, y) + ";\n";
    }

    public String formatPieceRef(int x, int y) {
        return "_board[" + (y - 1) + "][" + (x - 1) + "]";
    }

    public String reAssignVar(String ident, String body) {
        return ident + " = " + body + ";\n";
    }

    public String assignString(String ident, String body) {
        return "char *" + ident + ";\n"
                + ident + " = calloc(" + (body.length() + 1) + ", sizeof(char));\n"
                + "strcpy(" + ident + ", \"" + body + "\");\n";
    }

    public String reAssignString(String ident, String body) {
        return ident + " = realloc(" + ident + ", " + (body.length() + 1) + ");\n"
                + "strcpy(" + ident + ", " + body + ");\n";
    }

    public String assignNumber(String ident, String body) {
        return "int " + ident + " = " + body + ";\n";
    }

    public String reAssignNumber(String ident, String body) {
        return ident + " = " + body + ";\n";
    }

    public String assignBoolean(String ident, String body) {
        return assignNumber(ident, body);
    }

    public String reAssignBoolean(String ident, String body) {
        return reAssignNumber(ident, body);
    }

    public String formatLogicalOperator(String token) {
        return switch (token) {
            case "and" -> "&&";
            case "or" -> "||";
            case ">=" -> ">=";
            case "<=" -> "<=";
            case "==" -> "==";
            case "!=" -> "!=";
            case "<" -> "<";
            case ">" -> ">";
            default -> throw new RuntimeException("Unknown logical operator: " + token);
        };
    }

    public String formatPlace(String pieceIdent) {
        return """
                char _place_arg_x;
                int _place_arg_y;
                PLACE_INPUT:
                printf("Input: ");
                scanf("%c%d", &_place_arg_x, &_place_arg_y);
                int _in;
                while ((_in = getchar()) != EOF && _in != '\\n');
                """
                + "if (_current_player->" + pieceIdent + ".placeable && _current_player->" + pieceIdent
                + ".count < _current_player->" + pieceIdent + ".limit && _board[_place_arg_y - 1][_place_arg_x - ((int)'a')] == NULL) {\n"
                + "_board[_place_arg_y - 1][_place_arg_x - ((int)'a')] = &_current_player->" + pieceIdent + ";\n"
                + "_current_player->" + pieceIdent + ".count++;\n"
                + """
                } else {
                printf("Invalid piece placement! Try again:\\n");
                goto PLACE_INPUT;
                }
                """;
    }
}
