package com.company.codegen;

import com.company.Util;

public class TargetC implements TargetFormat {
    public String formatPieceDef(String ident, PieceDef pieceDef) {
        return
                ident + ".name = calloc(" + (pieceDef.props.name().length() + 1) + ", sizeof(char));\n"
                        + "strcpy(" + ident + ".name, \"" + pieceDef.props.name() + "\");\n"
                        + ident + ".limit = " + pieceDef.props.limit() + ";\n"
                        + ident + ".count = " + pieceDef.count + ";\n";
    }

    public String formatPlayerDef(PlayerDef playerDef) {
        var out = new StringBuilder();

        out.append("struct Player {\n");
        playerDef.player1.forEach((k, _v) -> out.append("  struct Piece ").append(k).append(";\n"));
        out.append("} _p1, _p2;\n");
        playerDef.player1.forEach((_k, v) ->
            out.append(v.toString())
        );
        playerDef.player2.forEach((_k, v) ->
            out.append(v.toString())
        );

        return out.toString();
    };

    public String formatSetup(SetupStruct setupStruct) {
        var out = new StringBuilder("""
                /*    SETUP    */
                """);

        out.append(setupStruct.playerDef)
                .append("struct Piece *_board[")
                .append(setupStruct.boardHeight)
                .append("][")
                .append(setupStruct.boardWidth)
                .append("] = {");

        for (PieceDef[] row : setupStruct.getBoard()) {
            out.append("{");
            for (PieceDef pieceDef : row)
                if (pieceDef != null) {
                    out.append("&")
                            .append(pieceDef.ownerPrefix)
                            .append(".")
                            .append(pieceDef.identifier)
                            .append(",");
                } else out.append("NULL,");

            out.append("},");
        }

        return out.append("};\n")
                .append(setupStruct.body.toString())
                .toString();
    }

    public String formatGame(String body) {
        return """
        /*   GAME    */
        struct Player _current_player;
        int _turn_count = 0;
        do {
        """
        + body
        + """
        } while (0);
        
        """;
    }

    public String format(SetupStruct setupStruct, GameStruct gameStruct) {
        return """
        /* === Code generated by Griddy compiler === */
        #include <stdio.h>
        #include <stdlib.h>
        #include <string.h>

        int main(int argc, char *argv[]){
        struct Piece { char* name; unsigned int limit; unsigned int count; };
        
        """
        + setupStruct
        + "\n"
        + gameStruct
        + """
        return 0;
        }
        """;
    }

    public String formatTurn(String playerPrefix, String body) {
        return "_current_player = " + playerPrefix + ";\n" + body + "\n";
    }

    public String outputString(String body) {
        return "printf(\"%s\\n\", " + body + ");\n";
    }

    public String outputNumber(String body) {
        return "printf(\"%d\\n\", " + body + ");\n";
    }

    public String outputTable(String ident, int w, int h) {
        /*
         *     printf("┌───┬───┬─── ... ┐\n");
         *     for (int _i = 0; _i < h; _i++) {
         *         for (int _j = 0; j < w; _j++)
         *             if (str_mtx[_i][_j]) {
         *                 printf("│ %s ", str_mtx[_i][_j]);
         *             } else printf("│   ");
         *         printf("│\n");
         *         if (h != _i + 1) printf("├───┼───┼─── ... ┤\n");
         *     }
         *     printf("└───┴───┴─── ... ┘\n");
         */
        var numberRow = new StringBuilder();
        for (int n : Util.range(1, w))
            numberRow.append("  ").append(n).append(" ");

        return "printf(\"┌───" + "┬───".repeat(Math.max(0, w - 1)) + "┐\\n\");\n"
                + "for (int _i = 0; _i < " + h + "; _i++) {\n"
                + "for (int _j = 0; _j < " + w + "; _j++)\n"
                + """
                if (_board[_i][_j]) {
                printf("│ %c ", *_board[_i][_j]->name);
                } else printf("│   ");
                printf("│ %c\\n", (char)('A' + _i));
                """
                + "if (" + h + " != _i + 1) printf(\"├───" + "┼───".repeat(Math.max(0, w - 1)) + "┤\\n\");\n}\n"
                + "printf(\"└───" + "┴───".repeat(Math.max(0, w - 1)) + "┘\\n\");\n"
                + "printf(\"" + numberRow + "\\n\");\n";
    }
}
